### ISSUE TITLE
[Bug]: Unable to select Skills in filter

### ISSUE THREAD

**Issue by pratheeshrussell-qb** [RJR-003/JS_Advanced_Assignment#10]
### Under which feature did you identify the bug?

filter

### Description

The skill filter checkbox gets selected at times but mostly it is not getting selected.

Note: The selection happens if I click somewhere away from the text or checkbox. Expected behaviour is it should be selected where ever I click within the yellow boundary

**Comment by RJR-003** [comment]
Have already fixed the issue
